'use client';import {useState} from 'react';
export default function ExtraTools({role,companies,sellers,onSaved}:{role:string;companies:{id:string;name:string}[];sellers:{id:string;name:string}[];onSaved:()=>void}){
 const [type,T]=useState('management'),[company,C]=useState(''),[parent,P]=useState(''),[name,N]=useState(''),[seller,S]=useState(''),[date,D]=useState(new Date().toISOString().slice(0,10)),[included,I]=useState(false),[msg,M]=useState(''),[hierarchy,H]=useState<any>({managements:[],teams:[]});
 const style={padding:10,margin:5,background:'#24344a',color:'white',border:'1px solid #64748b',borderRadius:8};
 async function load(){const r=await fetch('/api/hierarchy');if(r.ok)H(await r.json())}
 async function submit(url:string,data:any){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();M(r.ok?'Guardado correctamente':j.error||'Error');if(r.ok){onSaved();load()}}
 return <section style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(320px,1fr))',gap:16,marginTop:18}}>
 <article style={{padding:22,background:'#142137',borderRadius:14}}><h2>Venta individual</h2><form onSubmit={e=>{e.preventDefault();submit('/api/sales',{seller_id:seller,sale_date:date,mode:'individual',included_in_daily_count:included})}}><select style={style} required value={seller} onChange={e=>S(e.target.value)}><option value="">Vendedor</option>{sellers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input style={style} type="date" required value={date} onChange={e=>D(e.target.value)}/><p><label><input type="checkbox" checked={included} onChange={e=>I(e.target.checked)}/> Ya incluida en cantidad diaria</label></p><button style={style}>Registrar venta</button></form></article>
 {role==='admin'&&<article style={{padding:22,background:'#142137',borderRadius:14}}><h2>Administrar estructura</h2><button style={style} onClick={load}>Cargar jerarquía</button><form onSubmit={e=>{e.preventDefault();if(type==='company')submit('/api/companies',{name});else submit('/api/hierarchy',{type,name,company_id:company,...(type==='team'?{management_id:parent}:type==='seller'?{team_id:parent}:{})})}}><select style={style} value={type} onChange={e=>{T(e.target.value);P('')}}><option value="company">Empresa</option><option value="management">Gerencia</option><option value="team">Equipo</option><option value="seller">Vendedor</option></select>{type!=='company'&&<select style={style} required value={company} onChange={e=>{C(e.target.value);P('')}}><option value="">Empresa</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>}{(type==='team'||type==='seller')&&<select style={style} required value={parent} onChange={e=>P(e.target.value)}><option value="">Seleccionar superior</option>{(type==='team'?hierarchy.managements:hierarchy.teams).filter((x:any)=>x.company_id===company).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}<input style={style} required placeholder="Nombre" value={name} onChange={e=>N(e.target.value)}/><button style={style}>Crear</button></form></article>}
 <article style={{padding:22,background:'#142137',borderRadius:14}}><h2>Exportar</h2><p>Detalle mensual por empresa, gerencia, equipo y vendedor.</p><p>Usá el enlace de exportación del panel principal.</p></article>{msg&&<p role="status">{msg}</p>}</section>
}
