'use client';
import ExtraTools from './extra-tools';
import {useEffect,useState} from 'react';
export default function Home(){
 const [email,E]=useState(''),[password,P]=useState(''),[catalog,C]=useState<any>(null),[summary,S]=useState<any>(null),[month,M]=useState(new Date().toISOString().slice(0,7)),[seller,V]=useState(''),[date,D]=useState(new Date().toISOString().slice(0,10)),[qty,Q]=useState(1),[notice,N]=useState('');
 async function refresh(){const r=await fetch('/api/catalog');if(r.ok)C(await r.json())}
 useEffect(()=>{refresh()},[]);
 useEffect(()=>{if(catalog)fetch('/api/summary?month='+month).then(r=>r.json()).then(S)},[catalog,month]);
 async function login(e:any){e.preventDefault();const r=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const j=await r.json();if(r.ok){P('');refresh()}else N(j.error)}
 async function save(e:any){e.preventDefault();const r=await fetch('/api/sales',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({seller_id:seller,sale_date:date,mode:'daily',quantity:qty})});const j=await r.json();N(r.ok?'Guardado':j.error);if(r.ok)fetch('/api/summary?month='+month).then(x=>x.json()).then(S)}
 const panel={padding:22,background:'#142137',borderRadius:14,marginTop:18} as const;
 const input={padding:12,margin:8,background:'#24344a',color:'white',border:'1px solid #475569',borderRadius:8} as const;
 return <main style={{maxWidth:1100,margin:'auto',padding:30}}><h1>Control Diario</h1><p>Gestión comercial multiempresa</p>{notice&&<p role="status">{notice}</p>}{!catalog?<form style={panel} onSubmit={login}><h2>Ingresar</h2><input style={input} type="email" placeholder="Correo" value={email} onChange={e=>E(e.target.value)} required/><input style={input} type="password" placeholder="Contraseña" value={password} onChange={e=>P(e.target.value)} required/><button style={input}>Iniciar sesión</button></form>:<><button style={input} onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});C(null);S(null)}}>Cerrar sesión</button><section style={panel}><label>Mes <input type="month" style={input} value={month} onChange={e=>M(e.target.value)}/></label><h2>Ventas consolidadas: {summary?.companies?.reduce((a:number,c:any)=>a+Number(c.sales),0)??'—'}</h2><h3>Ranking por empresa</h3>{summary?.companies?.map((c:any)=><p key={c.company_id}>{c.company}: {c.sales} ventas {c.needs_review>0?'· Revisar '+c.needs_review:''}</p>)}</section>{catalog.role!=='analyst'&&<form style={panel} onSubmit={save}><h2>Registrar cantidad diaria</h2><select style={input} required value={seller} onChange={e=>V(e.target.value)}><option value="">Elegir vendedor</option>{catalog.sellers.map((s:any)=><option key={s.id} value={s.id}>{s.name} — {s.team}</option>)}</select><input style={input} required type="date" value={date} onChange={e=>D(e.target.value)}/><input style={input} required type="number" min="0" value={qty} onChange={e=>Q(Number(e.target.value))}/><button style={input}>Guardar</button></form>}<p><a style={{color:'#7dd3fc'}} href={'/api/report?month='+month}>Exportar CSV mensual</a></p><ExtraTools role={catalog.role} companies={catalog.companies} sellers={catalog.sellers} onSaved={()=>{refresh();fetch('/api/summary?month='+month).then(r=>r.json()).then(S)}}/></>}</main>
}
